---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
  namespace: orfns
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: orfns
  annotations:
    namea: $(SERVICES_GLOBAL_STATIC_IP_NAME)
    nameb: $(SERVICES_PRE_SHARED_CERT)
    hosta: $(HOST_A)
    hostb: $(HOST_B)
    hostc: $(HOST_C)

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/boreal-rain-256712/nginx
        ports:
        - containerPort: 80
