apiVersion: apps/v1
kind: Deployment
metadata:
  name: sun
  namespace: tsmpaloalto
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sun
  template:
    metadata:
      labels:
        app: sun
        version: v1
    spec:
      containers:
      - name: sun
        image: gcr.io/boreal-rain-256712/http-echo:latest
        env:
        - name: TEXT
          value: 'Sun Palo Alto -> '
        - name: NEXT
          value: "rain.duckbank.de:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sun
  namespace: tsmpaloalto
  labels:
    app: sun
spec:
  selector:
    app: sun
  ports:
  - name: http
    port: 8080
    targetPort: 8080
