---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-tsm-appparis
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-tsm-namespace
  interval: 1m0s
  path: /application1/tsm/apppaloalto
  prune: true
  sourceRef:
    kind: GitRepository
    name: gohjcicd                                  # Must match the name of the GitRepo you added in TMC
    namespace: tanzu-continuousdelivery-resources
