apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tanzu-auth.yaml
- tanzu-namespace.yaml
- tanzu-app.yaml
- tanzu-tsm-namespace.yaml
# - tanzu-tsm-appberlin.yaml # moved to TSM cluster1
# - tanzu-tsm-appparis.yaml  # moved to TSM cluster2
#
# Variable Test
#
- var-test-example-base.yaml
- var-test-example-overlay-stage.yaml
