# file: overlay/staging/kustomization.yaml
metadata:
  name: overlay-stage-kustomization
  namespace: orfns
  
configMapGenerator:
- name: ops-ingress-properties
  envs: [environment.properties]
  behavior: replace # <======= critical
