# file: overlay/staging/kustomization.yaml
metadata:
  name: overlay-stage-kustomization
namespace: tanzu-continuousdelivery-resources
  
configMapGenerator:
- name: ops-ingress-properties
  envs: [environment.properties]
  behavior: replace # <======= critical
